# Generated by Django 4.1.5 on 2023-01-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('title', models.CharField(max_length=400)),
                ('rating', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
