# Generated by Django 4.1.6 on 2023-02-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_size_productattribute_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1.Banner'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '3.Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2.Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '4.Colors'},
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': '8.details'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '6.product'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '7.productattributes'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '5.sizes'},
        ),
        migrations.AddField(
            model_name='details',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
