# Generated by Django 4.1.6 on 2023-02-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_banner_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Price_range',
        ),
        migrations.AlterModelOptions(
            name='price_range',
            options={'verbose_name_plural': '2.Price_range'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='Price_range',
        ),
    ]
