# Generated by Django 4.1.6 on 2023-02-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_category_price_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_range',
            name='image',
        ),
    ]
