# Generated by Django 4.1.6 on 2023-02-25 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_price_range_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_range',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cat_imgs/'),
            preserve_default=False,
        ),
    ]
